// Generated by using Rcpp::compileAttributes() -> do not edit by hand
// Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#include "../inst/include/xtensorrr.h"
#include <Rcpp.h>

using namespace Rcpp;

// xtensor_r_example
xt::rtensor<double, 2> xtensor_r_example(xt::rtensor<int, 1> tens);
RcppExport SEXP _xtensorrr_xtensor_r_example(SEXP tensSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< xt::rtensor<int, 1> >::type tens(tensSEXP);
    rcpp_result_gen = Rcpp::wrap(xtensor_r_example(tens));
    return rcpp_result_gen;
END_RCPP
}
// two_by_two_rarray
xt::rarray<double> two_by_two_rarray();
RcppExport SEXP _xtensorrr_two_by_two_rarray() {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    rcpp_result_gen = Rcpp::wrap(two_by_two_rarray());
    return rcpp_result_gen;
END_RCPP
}
// two_by_two_rtensor
xt::rtensor<double, 2> two_by_two_rtensor();
RcppExport SEXP _xtensorrr_two_by_two_rtensor() {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    rcpp_result_gen = Rcpp::wrap(two_by_two_rtensor());
    return rcpp_result_gen;
END_RCPP
}
// plus_one
xt::rarray<double> plus_one(xt::rarray<double> x);
RcppExport SEXP _xtensorrr_plus_one(SEXP xSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< xt::rarray<double> >::type x(xSEXP);
    rcpp_result_gen = Rcpp::wrap(plus_one(x));
    return rcpp_result_gen;
END_RCPP
}

static const R_CallMethodDef CallEntries[] = {
    {"_xtensorrr_xtensor_r_example", (DL_FUNC) &_xtensorrr_xtensor_r_example, 1},
    {"_xtensorrr_two_by_two_rarray", (DL_FUNC) &_xtensorrr_two_by_two_rarray, 0},
    {"_xtensorrr_two_by_two_rtensor", (DL_FUNC) &_xtensorrr_two_by_two_rtensor, 0},
    {"_xtensorrr_plus_one", (DL_FUNC) &_xtensorrr_plus_one, 1},
    {NULL, NULL, 0}
};

RcppExport void R_init_xtensorrr(DllInfo *dll) {
    R_registerRoutines(dll, NULL, CallEntries, NULL, NULL);
    R_useDynamicSymbols(dll, FALSE);
}
