# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

xtensor_r_example <- function(tens) {
    .Call(`_xtensorrr_xtensor_r_example`, tens)
}

two_by_two_rarray <- function() {
    .Call(`_xtensorrr_two_by_two_rarray`)
}

two_by_two_rtensor <- function() {
    .Call(`_xtensorrr_two_by_two_rtensor`)
}

plus_one <- function(x) {
    .Call(`_xtensorrr_plus_one`, x)
}

